# Generated by Django 3.0.4 on 2020-05-09 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('username', models.CharField(max_length=36, verbose_name='student name')),
                ('school', models.CharField(blank=True, choices=[(None, ''), ('بنين', 'بنين'), ('بنات', 'بنات')], max_length=4)),
                ('grade', models.CharField(blank=True, choices=[(None, ''), ('KG1', 'KG1'), ('KG2', 'KG2'), ('الأول الابتدائي', 'الأول الابتدائي'), ('الثاني الابتدائي', 'الثاني الابتدائي'), ('الثالث الابتدائي', 'الثالث الابتدائي'), ('الرابع الابتدائي', 'الرابع الابتدائي'), ('الخامس الابتدائي', 'الخامس الابتدائي'), ('الخامس الابتدائي', 'الخامس الابتدائي'), ('الأول الإعدادي', 'الأول الإعدادي'), ('الثاني الإعدادي', 'الثاني الإعدادي'), ('الثالث الإعدادي', 'الثالث الإعدادي'), ('الأول الثانوي', 'الأول الثانوي'), ('الثاني الثانوي', 'الثاني الثانوي'), ('الثالث الثانوي', 'الثالث الثانوي')], max_length=16)),
                ('payment_1', models.PositiveSmallIntegerField(default=0)),
                ('payment_2', models.PositiveSmallIntegerField(default=0)),
                ('study_paid', models.PositiveSmallIntegerField(default=0)),
                ('bus_active', models.BooleanField(default=False)),
                ('bus_fees', models.PositiveSmallIntegerField(default=0)),
                ('bus_paid', models.PositiveSmallIntegerField(default=0)),
                ('area', models.CharField(blank=True, choices=[(None, ''), ('aa', 'التجمع الخامس'), ('ab', 'مدينة نصر'), ('ac', 'القاهرة الجديدة'), ('ad', 'مصر الجديدة')], max_length=3)),
                ('adress', models.CharField(blank=True, max_length=32)),
                ('old_bus', models.CharField(blank=True, choices=[(None, ''), ('1001', '1001'), ('1002', '1002'), ('1003', '1003'), ('1004', '1004'), ('1005', '1005')], max_length=4)),
                ('message', models.CharField(blank=True, max_length=260)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
