# Generated by Django 3.0.4 on 2020-05-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='area',
            field=models.CharField(blank=True, choices=[(None, ''), ('التجمع الخام', 'التجمع الخامس'), ('مدينة نصر', 'مدينة نصر'), ('القاهرة الجديدة', 'القاهرة الجديدة'), ('مصر الجديدة', 'مصر الجديدة')], max_length=16),
        ),
    ]
