# Generated by Django 3.0.4 on 2020-05-09 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriptions', models.CharField(max_length=50, verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='تاريخ الإستحقاق')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(choices=[('11111111111111', '11111111111111'), ('22222222222222', '22222222222222'), ('33333333333333', '33333333333333'), ('44444444444444', '44444444444444'), ('55555555555555', '55555555555555'), ('نقدي بالمدرسة', 'نقدي بالمدرسة')], max_length=16)),
                ('value', models.PositiveSmallIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('دراسية', 'دراسية'), ('باص', 'باص')], max_length=6)),
                ('school', models.CharField(blank=True, choices=[(None, ''), ('بنين', 'بنين'), ('بنات', 'بنات')], max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
