# Generated by Django 3.0.4 on 2020-05-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DueDates',
        ),
    ]
